### ISSUE TITLE
Urls surrounded by parenthesis with a path are being parsed incorrectly.

### ISSUE THREAD

**Issue by lextoumbourou** [edmondburnett/twitter-text-python#10]
Hi @edburnett,

This works (and you've got a test for it :heart:):

``` python
In [1]: from ttp import ttp
In [2]: p = ttp.Parser()
In [3]: res = p.parse("test (http://example.com)")
In [4]: res.urls
Out[4]: ['http://example.com']
In [5]: res.html
Out[5]: u'test (<a href="http://example.com">http://example.com</a>)'
```

However, this does not:

``` python
In [6]: res = p.parse("test (http://example.com/directory)")
In [7]: res.urls
Out[7]: ['http://example.com/directory)']
In [8]: res.html
Out[8]: u'test (<a href="http://example.com/directory)">http://example.com/directory)</a>'
```

Note the right parentheses being treated as part of the URL?

Thanks,

Lex

**Comment by pjuu** [comment]
This isn't necersarily a bug as `)` is valid character in a URL path

**Comment by edmondburnett** [comment]
Since parentheses are valid within URLs, perhaps we could say that if there is an opening parentheses before the protocol, i.e. `(http://` AND a closing paren at the end of the URL, then only in that case we can ignore/strip them. Because then we could probably assume the user intended to enclose the URL inside parens.

**Comment by docapotamus** [comment]
@edmondburnett I think that sounds like a sensible solution.
